### ISSUE TITLE
导出的文本末尾多了些内容

### ISSUE THREAD

**Issue by ribber** [altairwei/Wiz.Format.Converter#2]
首先，老铁 666，我和你的用法基本一致，都是为知笔记配合 Editor.md 插件，之前一直纠结为知笔记如果倒了，笔记格式用的 html 存储，换到其他 MD 笔记平台麻烦，直到看到了你这个插件，真实太棒了

试了一下，末尾多了

```
![][0]

[0]: index_files/d46785a4-5439-436d-82b7-39fa99b9b968.jpg
```

**Comment by altairwei** [comment]
这是Markdown图片参考式语法，你用原生编辑器进入编辑状态，按F12打开开发工具，看看末尾是否有你不期望的`<img />`标签。另外，我在 release notes 中提到了，Editor.md 会自动转换 `<img />` 为 Markdown 图片语法，同时将原 `<img />` 隐藏掉（这是避免为知丢失图片）。所以，使用我这插件导出后，图片会重复，因为源文件经过 Editor.md 处理后本质上就会造成这种问题。

**Comment by ribber** [comment]
哦哦。是这样啊。
